<!DOCTYPE html>
<html>
	<head>
		<title>Philips Line Overview</title>
		<style>

		</style>
	</head>
	<body>
	
		<?php
		$servername = "localhost";
		$username = "rares";
		$password = "123";
		$dbname = "TV";
		$port = "3308";
		
		// Create connection
		$conn = new mysqli($servername, $username, $password, $dbname, $port);
		// Check connection
		if ($conn->connect_error) {
		  die("Connection failed: " . $conn->connect_error);
		}

		$sql = "SELECT id, data, time FROM overview";
		$result = $conn->query($sql);
		$linea = array();
		
		if ($result->num_rows > 0) {
		  // output data of each row
		  while($row = $result->fetch_assoc()) {
			$linea[] = $row["id"];
		  }
		} else {
		  echo "0 results";
		}
		
		$A = count($linea);
		$B = 192;
		$C = 282;
		$D = 348;
		$E = 443;
		$F = 536;
		$G = 615;
		$H = 700;
//---------------------SHIFT 3---------------------
		$I = 20;
		$J = 192;
		$K = 282;
		$L = 348;
		$M = 443;
		$N = 536;
		$O = 615;
		$P = 700;
//---------------------SHIFT 1---------------------		
		$Q = 2;
		$R = 192;
		$S = 282;
		$T = 348;
		$U = 443;
		$V = 536;
		$W = 615;
		$X = 700;
//---------------------SHIFT 2---------------------
	?>
	
	
		<center><H1>Philips Line Overview</H1></center>
		<br>
		<div class="names">
			<center>
			<table border="1">
			<tr><td>Linia</td><td>Detalii</td><td colspan="8">Schimbul 3</td><td colspan="8">Schimbul 1</td><td colspan="8">Schimbul 2</td></tr>
			<tr><td colspan="2">Ore</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			
			<tr><td rowspan="4">Omnia 1</td></tr>
			<tr><td>Target</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			<tr><td>Realizat</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			<tr><td>Status</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			
			<tr><td rowspan="4">Omnia 2</td></tr>
			<tr><td>Target</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			<tr><td>Realizat</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			<tr><td>Status</td><td>23-00</td><td>00-01</td><td>01-02</td><td>02-03</td><td>03-04</td><td>04-05</td><td>05-06</td><td>06-07</td><td>07-08</td><td>08-09</td><td>09-10</td><td>10-11</td><td>11-12</td><td>12-13</td><td>13-14</td><td>14-15</td><td>15-16</td><td>16-17</td><td>17-18</td><td>18-19</td><td>19-20</td><td>20-21</td><td>21-22</td><td>22-23</td></tr>
			
			

			
			
			</table>
			</center>
		</div>
	</body>
</html>