<html>
	<head>
		<title>Philips Line Overview</title>
		<style>
			.frames{
			margin-left: 30px;
			}
			
			iframe:focus {
  			outline: none;
			}
			
			h2{
				display-block: inline;
			}
		</style>
	</head>
	<body>
		<center><H1>Philips Line Overview</H1></center>
		<br>
		<div class="frames">
		<div class="names">
		<pre><h2>           Omnia 1                      Omnia 2                       TBA                         TBA                          TBA                          TBA</h2></pre>
		</div>  
			<iframe src="frames/omnia1.php" width="16%" height="72%"></iframe>
			<iframe src="frames/omnia2.php" width="16%" height="72%"></iframe>
			<iframe src="frames/1.html" width="16%" height="72%"></iframe>
			<iframe src="frames/2.html" width="16%" height="72%"></iframe>
			<iframe src="frames/3.html" width="16%" height="72%"></iframe>
			<iframe src="frames/4.html" width="16%" height="72%"></iframe>
		</div>
	</body>
</html>